sonar.projectKey=DevSecOps-Voting-App
sonar.projectName=DevSecOps-Voting-App
sonar.sources=vote,result
sonar.exclusions=**/node_modules/**,**/views/**
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
