
replicaCount: 1
images:
  vote:
    repository: 211116632423.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: 9c395d06ba506789082c894c3fd5dc24a815c53a
  result:
    repository: 211116632423.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: 9c395d06ba506789082c894c3fd5dc24a815c53a
  worker:
    repository: 211116632423.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: 9c395d06ba506789082c894c3fd5dc24a815c53a
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine
postgres:
  user: postgres
  password: postgres
  db: postgres
