
replicaCount: 1
images:
  vote:
    repository: 211116632423.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: fa0b024be02ffd01829450d6d0d728ba259cb834
  result:
    repository: 211116632423.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: fa0b024be02ffd01829450d6d0d728ba259cb834
  worker:
    repository: 211116632423.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: fa0b024be02ffd01829450d6d0d728ba259cb834
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine
postgres:
  user: postgres
  password: postgres
  db: postgres
