
replicaCount: 1
images:
  vote:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
    tag: c42add19b34d4fa0f10710e831d4ecffd13044da
  result:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
    tag: c42add19b34d4fa0f10710e831d4ecffd13044da
  worker:
    repository: 800557027783.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
    tag: c42add19b34d4fa0f10710e831d4ecffd13044da
  redis:
    repository: redis
    tag: 7-alpine
  db:
    repository: postgres
    tag: 15-alpine
postgres:
  user: postgres
  password: password
  db: postgres
