name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'DevSecOps-Voting-App'
        path: '.'
        format: 'HTML'
        args: >
          --failOnCVSS 7
          --enableRetired

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build VOTE
      run: docker build -t voting-app-vote:${{ github.sha }} ./vote

    - name: Scan VOTE with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'voting-app-vote:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true

    - name: Build RESULT
      run: docker build -t voting-app-result:${{ github.sha }} ./result

    - name: Scan RESULT with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'voting-app-result:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        ignore-unfixed: true

    - name: Build WORKER
      run: docker build -t voting-app-worker:${{ github.sha }} ./worker

    - name: Scan WORKER with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'voting-app-worker:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Push to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag voting-app-vote:$IMAGE_TAG $ECR_REGISTRY/voting-app-vote:$IMAGE_TAG
        docker tag voting-app-vote:$IMAGE_TAG $ECR_REGISTRY/voting-app-vote:latest
        docker push $ECR_REGISTRY/voting-app-vote:$IMAGE_TAG
        docker push $ECR_REGISTRY/voting-app-vote:latest
        
        docker tag voting-app-result:$IMAGE_TAG $ECR_REGISTRY/voting-app-result:$IMAGE_TAG
        docker tag voting-app-result:$IMAGE_TAG $ECR_REGISTRY/voting-app-result:latest
        docker push $ECR_REGISTRY/voting-app-result:$IMAGE_TAG
        docker push $ECR_REGISTRY/voting-app-result:latest
        
        docker tag voting-app-worker:$IMAGE_TAG $ECR_REGISTRY/voting-app-worker:$IMAGE_TAG
        docker tag voting-app-worker:$IMAGE_TAG $ECR_REGISTRY/voting-app-worker:latest
        docker push $ECR_REGISTRY/voting-app-worker:$IMAGE_TAG
        docker push $ECR_REGISTRY/voting-app-worker:latest
